version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3333:3333"
      - 27017:27017
    environment:
      - DB_HOST=database
    volumes:
      - ".:/usr/app"
      - ./database:/data/db

  database:
    image: mongo
